### ISSUE TITLE
MacOS catalina support

### ISSUE THREAD

**Issue by bttd** [diegoulloao/ioquake3-mac-install#2]
Hi,

The new MacOS cataline upgrade won't support 32 bit apps. It is possible to the script install a 64 bit version?

**Comment by diegoulloao** [comment]
I don’t know a way to install 64bits version on macOs. ¿Do you know it?

**Comment by bttd** [comment]
Hi,

I can compile on Catalina the 64 bit version: 
https://drive.google.com/file/d/1KkjmzvuEeYQ6A3-Ut26X2Lu0psZ4NMJj/view?usp=sharing

You need to install older SDKs and Compile it with the included script, with x86_64 arg.

I can't find the way on ioquake github. The launcher doesn't have instruction since ioquake wiki won't work, and I don't can compile it.

**Comment by diegoulloao** [comment]
I’ll try to do something with that. Do you help me to test then?

Regards.

**Comment by bttd** [comment]
Hi, 

Yes I can test it. The app what I linked from my google drive, works, if I just replace the ioqake-1.36.app, later I can test it on older Mojave macOS.

**Comment by diegoulloao** [comment]
Perfect. It’s works definitely but I need achieve the same with ioquake3fe-1.36 file.
I can see problems with CPMA too, I’ll try with the latest version released.

Please tell me what happend with Mojave.

Thank you.

**Comment by diegoulloao** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Hey bro! Can you test the following dev branch pls?https://github.com/diegoulloao/ioquake3-mac-install/tree/devIt’s in process. Now I need to convert ioquake3fe-1.36 file to 64 bits.Any idea?Thanks.  

Diego Ulloa. { diegoulloao@icloud.com }Programador - Desarrollador.--www.diegoulloa.cl El 10 de octubre de 2019 a las 17:01:15, Diego Ulloa. (diegoulloao@icloud.com) escribió: 







Perfect.
It’s works definitely but I need achieve the same
with ioquake3fe-1.36 file.
I can see
problems with CPMA too, I’ll try with the latest version
released.


Please
tell me what happend with Mojave.
Thank
you.





Diego Ulloa. { diegoulloao@icloud.com
}
Programador -
Desarrollador.
--
www.diegoulloa.cl




El 10 de octubre de 2019 a las 16:57:39, bttd
(notifications@github.com)
escribió:



Hi,
Yes I can test it. The app what I linked from my google
drive, works, if I just replace the ioqake-1.36.app, later I can
test it on older Mojave macOS.

—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by diegoulloao** [comment]
Hey bro! Can you test the following dev branch pls?

(need to remove old directories, ioquake3 in Applications and Quake3 in ~/Library/Application Support)

https://github.com/diegoulloao/ioquake3-mac-install/tree/dev

It’s in process. Now I need to convert ioquake3fe-1.36 file to 64 bits.

Any idea?

Thanks.

**Comment by bttd** [comment]
Dev branch works for me except launcher. I try to find a way to compile it on x86_64.

Another problem. Most of the time I try this game on an external monitor. If I try it on my built-in retina display, the game runs on the bottom 1/3 off the screen. 
I think this is a known problem, so I'm trying to find the solution.

Later I try to test it on Mojave too.

**Comment by diegoulloao** [comment]
Okay bro.

I try game with external 27" Thunderbolt Display and this works fine.
Later i'll try on my retina notebook screen.

I'm improving some things of external dependencies and files management, improving the script too.

Thanks a lot for all the support man. Let's do this!
Waiting for news ;)

**Comment by diegoulloao** [comment]
@all-contributors please add @bttd for 64-bits executables compiling and test

**Comment by diegoulloao** [comment]
@bttd let's continue in this thread pls: https://github.com/diegoulloao/ioquake3-mac-install/issues/3

**Comment by diegoulloao** [comment]
> Another problem. Most of the time I try this game on an external monitor. If I try it on my built-in retina display, the game runs on the bottom 1/3 off the screen.
> I think this is a known problem, so I'm trying to find the solution.

Problem solved !

Solution here: https://github.com/ioquake/ioq3/issues/422

**Comment by diegoulloao** [comment]
@all-contributors please add @rcgordon for bug and code

**Comment by diegoulloao** [comment]
**Master v3 is here!**

**https://github.com/diegoulloao/ioquake3-mac-install**

Thank you for all!

@bttd
